#
# Module manifest for module 'Scout'
#
# Generated by: Ariadne Rangel
#
# Generated on: 9/28/2024
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'Scout.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0'

    # ID used to uniquely identify this module
    GUID              = 'fa36ba6a-82ea-43ef-82ec-73ba94c50c9b'

    # Author of this module
    Author            = 'Ariadne Rangel'

    # Company or vendor of this module
    CompanyName       = 'Ariadne Rangel'

    # Copyright statement for this module
    Copyright         = '2024 Ariadne Rangel'

    # Description of the functionality provided by this module
    Description       = 'Utility module for generating text and HTML templates.'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = '*'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @("Template-engine", "Template-utility", "HTML-Templates", "Text-Templates")

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/AriDevK/Scout-PS?tab=GPL-3.0-1-ov-file'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/AriDevK/Scout-PS'

        } # End of PSData hashtable

    } # End of PrivateData hashtable
}
